name: buildDockerImage

on:
  push:
    branches:
      - 'master'

jobs:
  build_matrix:
    strategy:
      matrix:
        feature: [voce, matrix]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.${{ matrix.feature }}
          platforms: linux/${{ matrix.arch }}
          tags: chikage/yande_popular:${{ matrix.feature }}
